name: .NET 7 Build and Test

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x' 

    - name: Restore dependencies
      run: dotnet restore "Challenge-ShawAndPartners.sln" 

    - name: Build
      run: dotnet build "Challenge-ShawAndPartners.sln" --no-restore -c Release 

    - name: Run tests
      run: dotnet test "Challenge-ShawAndPartners.sln" --no-build -c Release --verbosity normal 
